name: AMUL Stock Check

on:
  schedule:
    - cron: '0 */4 * * *' # Runs every 4 hours
  workflow_dispatch:

jobs:
  check-stock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run stock check script
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          EMAIL_RECIPIENT: "dhruvkotwani@outlook.com, sejalbudhani@outlook.com"
          PYTHONPATH: .
        run: |
          for i in 1 2 3 4 5; do
            python app/main.py && break || echo "Attempt $i failed, retrying in 10 seconds..." && sleep 10
          done